### ISSUE TITLE
Two independent implementations?

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-3-wg-charter#19]
When some feature is used by commercial EPUB publications and is supported by ONE reading system?  I would strongly argue that this feature should not be dropped.  Thus, I would like to drop the first paragraph in 3. Success Criteria.

**Comment by dauwhe** [comment]
How can we demonstrate a feature is interoperable with only one implementation? This would also seem to be evidence that the market is not interested in the feature, as if it was useful others would likely implement it. 

Do you know of any such features?

**Comment by murata2makoto** [comment]
> Do you know of any such features?

Suppose that align-x-center is supported by one implementation and is used by some publishers.

**Comment by iherman** [comment]
If a feature is implemented by only one reading system (and that is what our tests show) it does not automatically mean that the feature is _removed_ from the specification; that is a separate decision of the Working Group. It _may_ just mean that this is kept but not as a _standard_ feature but, instead, as a documented, but "informative" feature describing a single, product specific feature (which is _exactly_ what it is).

That does not change the text of the success criteria, which is for _standard_, ie, recommended features.

**Comment by wareid** [comment]
Everything Ivan said!

I'd also add that considering the number of in-market implementations of EPUB in all it's flavours, if there's an implementation of something used exclusively by one reading system only, I think it's worth looking at why that has happened. Is there either something they could do differently that the spec hasn't made clear to them, or is that feature actually more usable, but the spec does not provide conformance information that is universally understood.

**Comment by murata2makoto** [comment]
@iherman 

Sorry, I am puzzled by "informative feature".  Is a document containing this feature conformant?  Or, is it non-conformant?  This is a black-and-white question.

**Comment by iherman** [comment]
Considering this feature, and this feature alone, the issue of conformance does not apply. Conformance of a document (or a reading system) is only relevant in view of the normative features.

This is the "legal" aspect. In practice, one can discuss whether these features are checked (or not) by epubcheck. But that is not the WG's decision.

**Comment by murata2makoto** [comment]
@iherman 

Sorry, I still do not understand.  Suppose that align-x-center is marked as "informative feature".  Is an EPUB publication containing conformant or non-conformant?  I strongly believe that conformance is the most important thing in standardization.

**Comment by iherman** [comment]
If a document is _**otherwise conformant**_, ie, if it is conformant vis-a-vis all features it uses and _**are**_ normative, and `align-x-center` is marked as an "informative feature" then yes, it is conformant.

**Comment by murata2makoto** [comment]
Are there any W3C recommendations that provide "informative features"?

**Comment by iherman** [comment]
> Are there any W3C recommendations that provide "informative features"?

Some examples in my own practice:

- JSON-LD 1.1 (will go to PR very soon, maybe next week), e.g., [“The rdf:CompoundLiteral class and the rdf:language and rdf:direction properties”](https://www.w3.org/TR/json-ld11/#the-rdf-compoundliteral-class-and-the-rdf-language-and-rdf-direction-properties)
- Annotation Model, e.g., [“Additional Media Types/Selector Combination”](https://www.w3.org/TR/annotation-model/#additional-media-types-selector-combination)
- Generating RDF from Tabular Data on the Web, e.g., [“Inclusion of provenance information”](https://www.w3.org/TR/csv2rdf/#provenance)

I am sure there are more.

**Comment by murata2makoto** [comment]
@iherman Thanks.  I am flabbergasted.  In the ISO world, something can be informative only when it can be safely dropped without any impacts on conformance.

**Comment by dauwhe** [comment]
> If a feature is implemented by only one reading system (and that is what our tests show) it does not automatically mean that the feature is _removed_ from the specification; that is a separate decision of the Working Group. It _may_ just mean that this is kept but not as a _standard_ feature but, instead, as a documented, but "informative" feature describing a single, product specific feature (which is _exactly_ what it is).

@iherman, is there documentation of this? I don't see anything in the regular process document.

**Comment by swickr** [comment]
@murata2makoto ,
> 
> @iherman
> 
> Sorry, I still do not understand. Suppose that align-x-center is marked as "informative feature". Is an EPUB publication containing conformant or non-conformant? I strongly believe that conformance is the most important thing in standardization.

Conformance to a W3C spec is often defined explicitly within that spec.  W3C precedent is that features that affect conformance are explicitly so stated as normative.  Recent specifications are also frequently even more explicit about this; identifying how normative sections and non-normative (aka "informative") are marked.  A very recent example is the W3C [Web of Things Description](https://www.w3.org/TR/2020/REC-wot-thing-description-20200409/) Recommendation.  [Section 2](https://www.w3.org/TR/2020/REC-wot-thing-description-20200409/#conformance) of that Recommendation describes conformance to that specification and [section 7](https://www.w3.org/TR/2020/REC-wot-thing-description-20200409/#sec-context-extensions) contains some material that is outside that conformance statement.

It would be acceptable for a conformance-checking tool (such as a future version of EPUBCheck) to ignore non-normative assertions in a spec or to have a mode that provided informative notices of violations of non-normative assertions.  It would not be appropriate for a conformance-checking tool to mark something as non-conformant solely because it failed to implement a non-normative feature or implemented it in a different manner than was described in the spec.

This flexibility allows a W3C Recommendation to include experimental features or to document features that had not yet demonstrated interoperable implementations by omitting such features from its definition of conformance.

**Comment by murata2makoto** [comment]
@iherman and @swickr It appears that I have to learn more about current practices in W3C.  (I'm not sure if I agree, though.)  But I am relieved to hear that you do not intend to automatically drop features that do not satisfy the "Two independent implementations" criteria.  Agree to close this issue.
